version: "3.9"

services:
  relayserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: dreamcacao/relaydns:latest
    command:
      - "--http"
      - ":8080"
      # To add bootstraps, add more lines like below (repeatable):
      # - "--bootstrap"
      # - "/dnsaddr/bootstrap.example/p2p/12D3Koo..."
    ports:
      - "8080:8080"     # Admin UI + HTTP proxy
      - "4001:4001/tcp" # libp2p tcp
      - "4001:4001/udp" # libp2p quic/udp
    restart: unless-stopped
